#!/usr/bin/env lua

package.path = "./lib/?.lua;" .. package.path

local Discover = require "discover"
local Reader = require "reader"
local Metadata = require "metadata"
local Manifest = require "manifest"
local Reporter = require "reporter"
local json = require "json"

local function usage()
   print([[

Usage:

     artifact <command> [options]

      ]])
end

local function show_help()
   print([[

Artifact

Usage:
     artifact <command> [options]

Commands:
     discover
     read
     validate
     manifest
     build

Options:
    -h, --help

]])
end

local command = arg[1]

if command == "-h" or command == "--help" then
   show_help()
   os.exit(0)
end

if command == "discover" then
   local files = Discover.run(arg[2] or "content")

   for _, file in ipairs(files) do
      print(file)
   end
   
elseif command == "read" then
   local files

   if arg[2] then
      files = { arg[2] }
   else
      files = Discover.run()
   end

   for _, path in ipairs(files) do
      local document = Reader.read(path)

      Metadata.extract(document)

      print(json.pretty(document))
   end

elseif command == "manifest" then
   -- local paths = Discover.run(arg[2] or "content")

   local manifest = Manifest.build(arg[2])

   print(json.pretty(manifest))

elseif command == "validate" then
   local manifest = Manifest.build(arg[2])

   Reporter.validation(manifest)
   print("documents:", #manifest)

   local errors = 0

   for _, document in ipairs(manifest) do
      -- print(document.path, #document.diagnostics)
      
      if #document.diagnostics > 0 then
	 errors = errors + 1

	 print(document.path)

	 for _, diagnostic in ipairs(document.diagnostics) do
	    print(string.format(
		     "  [%s] %s: %s",
		     diagnostic.severity:upper(),
		     diagnostic.field,
		     diagnostic.message
	    ))
	 end

	 print()
      end
   end

   if errors == 0 then
      print("Validation succesful.")
   else
      print(string.format(
	       "%d document(s) contain diagnostics.",
	       errors
      ))

      os.exit(1)
   end

else
   io.stderr:write("\nError unknow command: " .. tostring(command) .. "\n")
   usage()
   os.exit(1)
end
