#!/usr/bin/env lua

package.path = "./lib/?.lua;" .. package.path

local Discover = require "discover"
local Reader = require "reader"
local Metadata = require "metadata"
local json = require "json"

local function usage()
   print([[

Usage:

     artifact <command> [options]

      ]])
end

local function show_help()
   print([[

Artifact

Usage:
     artifact <command> [options]

Commands:
     discover
     read
     validate
     manifest
     build

Options:
    -h, --help

]])
end

local command = arg[1]

if command == "-h" or command == "--help" then
   show_help()
   os.exit(0)
end

if command == "discover" then
   local files = Discover.run(arg[2] or "content")

   for _, file in ipairs(files) do
      print(file)
   end
   
elseif command == "read" then
   local files = Discover.run()

   for _, path in ipairs(files) do
      local document = Reader.read(path)

      Metadata.extract(document)

      print(json.pretty(document))
   end
   
else
   io.stderr:write("\nError unknow command: " .. tostring(command) .. "\n")
   usage()
   os.exit(1)
end
